### ISSUE TITLE
Random question

### ISSUE THREAD

**Issue by SIB-BYTE** [mathletedev/game-of-life#1]
Hey man, do you have discord? I have several questions regarding the code and your video about the code.

**Comment by neowsl** [comment]
Hello! You can join this server:
https://discord.gg/RRfW8FrX3E/

**Comment by SIB-BYTE** [comment]
Hey man, this just directs me to the discord website and doesn't actually prompt me to join a server. Add my discord: λx.x#4033

**Comment by neowsl** [comment]
You can just ask them here if you want
